### ISSUE TITLE
千里送人头？

### ISSUE THREAD

**Issue by newBBnew** [Mob2003/rakshasa#2]
这个设计理念不太符合安全要求吧！
假设A机器是自己的，B机器是别人的，C机器也是别人的。
1、B机器连上A以后，A直接就被控了，A原本只想要B和C的网络以及权限，我这不是千里送人头吗？
2、B、C机器被任何人攻陷后，直接能通过历史命令发现连接密码，A又直接被控了；
3、假设整个网中任何一台失陷，所有机器都惨了；

**Comment by Mob2003** [comment]
A是自己的，b怎么连接a你加我微信吧，跟我说说，Mob20045这是我微信号

**Comment by Mob2003** [comment]
我没看懂，你是怎么连接a的，被控端，服务端，被控端怎么控制服务端？建议看看tcp原理

**Comment by newBBnew** [comment]
比如B是被攻陷的一台肉鸡，想进一步获取B内网其它权限（横向移动），只能让B反连A，结果连到A以后，B居然能操作A机器权限，这还咋玩啊

**Comment by Mob2003** [comment]
你加我微信吧，不会出现你说的情况



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: newBBnew ***@***.***&gt;
发送时间: 2023年4月3日 08:45
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Mob2003 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 千里送人头？ (Issue #2)





 
比如B是被攻陷的一台肉鸡，想进一步获取B内网其它权限（横向移动），只能让B反连A，结果连到A以后，B居然能操作A机器权限，这还咋玩啊

**Comment by Mob2003** [comment]
不会出现你说的，他不会反连的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: newBBnew ***@***.***&gt;
发送时间: 2023年4月3日 08:45
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Mob2003 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 千里送人头？ (Issue #2)





 
比如B是被攻陷的一台肉鸡，想进一步获取B内网其它权限（横向移动），只能让B反连A，结果连到A以后，B居然能操作A机器权限，这还咋玩啊
