### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by peiqiF4ck** [Mob2003/rakshasa#5]
建议博主参考这个多级代理工具https://github.com/Dliv3/Venom 使用越简单工具越好。可惜的是不更新了很多功能没有完善。

**Comment by Mob2003** [comment]
我没看过，而且我有个lite版本，只有一个转发功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 明天会更好 ***@***.***&gt;
发送时间: 2023年4月8日 11:01
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 建议 (Issue #5)





 
建议博主参考这个多级代理工具https://github.com/Dliv3/Venom 使用越简单工具越好。

**Comment by peiqiF4ck** [comment]
我希望博主参考一下别人的项目你得项目和其他人项目融合到一块。取长补短。好的项目就是使用越简单功能强大。而不是使用复杂功能强大。项目无非两种。盈利和获取名气。简历上写xxx项目几千star是我写的这很牛逼，盈利的就不说了。感谢博主回复。希望可以加强一下你的这个工具我还没用等我用一下看看效果如何。另外可以增加点使用场景案例demo。发到github我们是希望看git就可以食用而不是另辟蹊径。创建群或者干啥是反馈软件的功能或者是有人定制开发这种。不是加群以后加联系方式以后。索要食用方法。最后希望博主工具可以在内网渗透代理穿透类工具里面排第一。

**Comment by Mob2003** [comment]
谢谢建议，你的建议会使我变的更加强大，我是一个人，不是团队，我后面还有6个开源，等到时候看一下使软件更加完善



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 明天会更好 ***@***.***&gt;
发送时间: 2023年4月8日 11:21
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Mob2003 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 建议 (Issue #5)





 
我希望博主参考一下别人的项目你得项目和其他人项目融合到一块。取长补短。好的项目就是使用越简单功能强大。而不是使用复杂功能强大。项目无非两种。盈利和获取名气。简历上写xxx项目几千star是我写的这很牛逼，盈利的就不说了。感谢博主回复。希望可以加强一下你的这个工具我还没用等我用一下看看效果如何。另外可以增加点使用场景案例demo。发到github我们是希望看git就可以食用而不是另辟蹊径。创建群或者干啥是反馈软件的功能或者是有人定制开发这种。不是加群以后加联系方式以后。索要食用方法。最后希望博主工具可以在内网渗透代理穿透类工具里面排第一。

**Comment by peiqiF4ck** [comment]
我也是一个人开发。努力使我们的项目获取更多人气。同时如果能获取利润当然是更好的。

**Comment by Mob2003** [comment]
加个微信聊一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 明天会更好 ***@***.***&gt;
发送时间: 2023年4月8日 13:33
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Mob2003 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 建议 (Issue #5)





 
我也是一个人开发。努力使我们的项目获取更多人气。同时如果能获取利润当然是更好的。

**Comment by Mob2003** [comment]
加我微信聊聊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 明天会更好 ***@***.***&gt;
发送时间: 2023年4月8日 13:33
收件人: Mob2003/rakshasa ***@***.***&gt;
抄送: Mob2003 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mob2003/rakshasa] 建议 (Issue #5)





 
我也是一个人开发。努力使我们的项目获取更多人气。同时如果能获取利润当然是更好的。

**Comment by peiqiF4ck** [comment]
微信就不加了。感谢作者辛苦更新和回复。wx容易泄露隐私信息。你懂得
